Fix QAT and quantize, add configs for Llama3.1 and 3.2
**Summary:** This commit addresses three issues.

1. The quantize recipe fails with `.safetensors` extensions
2. QAT configs for Llama3-8B have incorrect model paths
3. Missing QAT full configs for Llama3.1 and 3.2
   (only QAT + LoRA exists today)

For (1), if you quantize a model using the default
`.safetensors` extension, you will run into the following error
when loading the model:

```
Traceback (most recent call last):
  File "/home/andrewor/local/torchtune/torchtune/training/checkpointing/_utils.py", line 254, in safe_torch_load
    with safe_open(checkpoint_path, framework="pt", device="cpu") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

We fix this with an arbitrary `.cpkt` extension instead.
Seems like pathlib has some special handling for `.safetensors`.

**Test Plan:**

```
# finetune
tune run --nnodes 1 --nproc_per_node 4 qat_distributed --config llama3/8B_qat_full \
    epochs=1 \
    batch_size=16 \
    dataset._component_=torchtune.datasets.alpaca_cleaned_dataset \
    checkpointer.output_dir=/home/andrewor/local/logs/tune/Llama3-8B_qat \
    output_dir=/home/andrewor/local/logs/tune/Llama3-8B_qat/metrics \
    metric_logger.log_dir=/home/andrewor/local/logs/tune/Llama3-8B_qat/metrics \
    quantizer._component_=torchtune.training.quantization.Int8DynActInt4WeightQATQuantizer \
    quantizer.groupsize=32

# quantize
tune run quantize --config quantization \
    model._component_=torchtune.models.llama3.llama3_8b \
    checkpointer._component_=torchtune.training.FullModelHFCheckpointer \
    checkpointer.checkpoint_dir=/home/andrewor/local/logs/tune/Llama3-8B_qat/epoch_0 \
    checkpointer.output_dir=/home/andrewor/local/logs/tune/Llama3-8B_qat/epoch_0_quantized \
    'checkpointer.checkpoint_files=[model-00001-of-00004.safetensors,model-00002-of-00004.safetensors,model-00003-of-00004.safetensors,model-00004-of-00004.safetensors]' \
    checkpointer.model_type=LLAMA3 \
    quantizer._component_=torchtune.training.quantization.Int8DynActInt4WeightQuantizer \
    quantizer.groupsize=32

# eval
tune run eleuther_eval --config eleuther_evaluation \
    batch_size=1 \
    'tasks=[hellaswag]' \
    model._component_=torchtune.models.llama3.llama3_8b \
    checkpointer._component_=torchtune.training.FullModelTorchTuneCheckpointer \
    checkpointer.checkpoint_dir=/home/andrewor/local/logs/tune/Llama3-8B_qat/epoch_0_quantized \
    checkpointer.output_dir=/home/andrewor/local/logs/tune/Llama3-8B_qat/epoch_0_eval \
    'checkpointer.checkpoint_files=[model-00001-of-00004-8da4w.ckpt]' \
    checkpointer.model_type=LLAMA3 \
    tokenizer._component_=torchtune.models.llama3.llama3_tokenizer \
    tokenizer.path=/tmp/Meta-Llama-3-8B-Instruct/original/tokenizer.model \
    quantizer._component_=torchtune.training.quantization.Int8DynActInt4WeightQuantizer \
    quantizer.groupsize=32
```